// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMNFNU5Dr_Q265yJ8qlIoF7dkihuHbdYg',
    appId: '1:645235231624:web:269942c1e9bfc8853d083d',
    messagingSenderId: '645235231624',
    projectId: 'wearwise25',
    authDomain: 'wearwise25.firebaseapp.com',
    storageBucket: 'wearwise25.firebasestorage.app',
    measurementId: 'G-C8KHGRXGNV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBtc_GyrBCQJwb_guHyH3v6s1sGu9Ai1U',
    appId: '1:645235231624:android:0c6f12b29f20c0fb3d083d',
    messagingSenderId: '645235231624',
    projectId: 'wearwise25',
    storageBucket: 'wearwise25.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrk4PPlh-cP2PX7cNfhuAJ6cYsr2YOB5A',
    appId: '1:645235231624:ios:2636904cd165bd7b3d083d',
    messagingSenderId: '645235231624',
    projectId: 'wearwise25',
    storageBucket: 'wearwise25.firebasestorage.app',
    iosBundleId: 'com.example.wearwise',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrk4PPlh-cP2PX7cNfhuAJ6cYsr2YOB5A',
    appId: '1:645235231624:ios:2636904cd165bd7b3d083d',
    messagingSenderId: '645235231624',
    projectId: 'wearwise25',
    storageBucket: 'wearwise25.firebasestorage.app',
    iosBundleId: 'com.example.wearwise',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMNFNU5Dr_Q265yJ8qlIoF7dkihuHbdYg',
    appId: '1:645235231624:web:07640ca55f4487263d083d',
    messagingSenderId: '645235231624',
    projectId: 'wearwise25',
    authDomain: 'wearwise25.firebaseapp.com',
    storageBucket: 'wearwise25.firebasestorage.app',
    measurementId: 'G-ZX3ZK13S4E',
  );

}